import dns from "node:dns";
dns.setServers(['8.8.8.8', '8.8.4.4']);
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NextThemeProvider from "@/providers/NextThemeProvider";
import { ToastContainer } from "react-toastify";

const outfit = Outfit({
  subsets: ["latin"],
});


export const metadata = {
  title: "Add Idea | IdeaVault",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      suppressHydrationWarning
      className={`${outfit.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground" cz-shortcut-listen="true">
        <NextThemeProvider>
          <Navbar></Navbar>
        {children}
        <Footer></Footer>
        <ToastContainer />
        </NextThemeProvider>
      </body>
    </html>
  );
}
